FROM php:fpm

RUN apt-get update && apt-get install -y \
        libpq-dev \
        curl \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql

CMD ["php-fpm"]